SRC += 	mine.c \
		process_records.c

AUDIO_ENABLE = no
BACKLIGHT_ENABLE = no
BLUETOOTH_ENABLE = no
BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
DEBUG_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MIDI_ENABLE = no
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = no
RGBLIGHT_ENABLE ?= no
SLEEP_LED_ENABLE = no
SPACE_CADET_ENABLE = no
SWAP_HANDS_ENABLE = no
TAP_DANCE_ENABLE = no
UNICODE_ENABLE = no
LTO_ENABLE = yes
